Ae 800/include assets in report
org-metaeffekt/metaeffekt-core pull request #159
Opened 2024-11-07 14:01 UTC by jfuegen-metaeffekt

Added assets to component vulnerabilites section and created a section with assets listing contained components. Added links to ease traversal.

2024-11-08 07:04 UTC, YanWittmann commented on plugins/ae-inventory-maven-plugin/src/main/java/org/metaeffekt/core/maven/inventory/mojo/PomReportCreationMojo.java
> +    private Inventory  createInventoryFromPom() {
I love this additional space that was added here

2024-11-08 07:07 UTC, YanWittmann commented on libraries/ae-inventory-processor/src/main/java/org/metaeffekt/core/inventory/processor/report/adapter/AssetReportAdapter.java
> +
Why such empty line

2024-11-08 07:26 UTC, YanWittmann requested changes
Okay, I think we're going to chat a little about these changes to align them with the rest of the codebase and a couple of other things.

2024-11-08 07:26 UTC, YanWittmann commented on libraries/ae-inventory-processor/src/main/java/org/metaeffekt/core/inventory/processor/report/model/aeaa/AeaaVulnerabilityContextInventory.java
> +                            vulnerability.manuallyAffectsAssets(InventoryUtils.getAssetsForArtifact(inventory,
- If you change something in a class prefixed with `Aeaa`, you will have to find the corresponding file in the [Artifact Analysis project](https://github.com/org-metaeffekt/metaeffekt-artifact-analysis/blob/429b60a1103db79ad083db179561d7d19e689107/modules/ae-artifact-analysis/src/main/java/com/metaeffekt/mirror/contents/base/VulnerabilityContextInventory.java#L44) to update as well.
- The same goes for the `Vulnerability` and it's superclasses.

2024-11-08 07:26 UTC, YanWittmann commented on libraries/ae-inventory-processor/src/main/java/org/metaeffekt/core/inventory/processor/report/model/aeaa/AeaaMatchableDetailsAmbDataClass.java
> +	protected final Set<AssetMetaData> affectedAssets = new HashSet<>();
This information should not be stored in a property, but rather recalculated upon any access to the vulnerability instance using the `affectedArtifacts`.
Storing this information would surely lead to sync-issues in the future, having to always update the information in two properties (redundancy leads to inconsistency).

Also, if we were to update this file, the according class in the artifact analysis project would have to be updated as well.

2024-11-08 07:26 UTC, YanWittmann commented on libraries/ae-inventory-processor/src/main/java/org/metaeffekt/core/inventory/processor/report/model/aeaa/AeaaMatchableDetailsAmbDataClass.java
Please do not generally apply a new auto-formatter to an entire existing file.
As this file is a mere copy of a file in artifact analysis, it is important that the same formatting remains, as it allows for easily comparing the two for changes made in either of them to apply them to the other.

2024-11-08 07:26 UTC, YanWittmann commented on libraries/ae-inventory-processor/src/main/java/org/metaeffekt/core/inventory/processor/report/model/aeaa/AeaaMatchableDetailsAmbDataClass.java
What I want to say is, please restore the original formatting and only change the lines you need to.

2024-11-08 07:26 UTC, YanWittmann commented on libraries/ae-inventory-processor/src/main/java/org/metaeffekt/core/inventory/processor/report/adapter/VulnerabilityReportAdapter.java
See my comment on the class `AeaaMatchableDetailsAmbDataClass` regarding the formatting.

2024-11-08 07:26 UTC, YanWittmann commented on libraries/ae-inventory-processor/src/main/java/org/metaeffekt/core/inventory/InventoryUtils.java
Please see my comment on `AeaaMatchableDetailsAmbDataClass`.

2024-11-08 07:26 UTC, YanWittmann commented on libraries/ae-inventory-processor/src/test/java/org/metaeffekt/core/inventory/processor/report/AssessmentInventoryMergerTest.java
Please see `AssessmentInventoryMergerTest`. Also, we do not use tabs for indentation, but rather spaces.

2024-11-10 14:34 UTC, closed without merging

2024-11-10 14:35 UTC, karsten-klein commented
Decided to cherry-pick and review. Relevant changes have been merged to core