OSV-Report Integration
org-metaeffekt/metaeffekt-core pull request #178
Opened 2024-12-05 11:13 UTC by juliankomarek

Added OSV-Related files and contents for Report purposes.

2024-12-09 07:47 UTC, karsten-klein commented on libraries/ae-inventory-processor/src/main/java/org/metaeffekt/core/inventory/processor/report/model/aeaa/store/AeaaAdvisoryTypeStore.java
> +            AeaaOsvAdvisorEntry.class, AeaaOsvAdvisorEntry::new);
Why is GHSA equivalent to OSV?

2024-12-09 07:47 UTC, karsten-klein commented on libraries/ae-security/src/main/java/org/metaeffekt/core/security/cvss/KnownCvssEntities.java
> +    public final static CvssEntity OSV = ObjectUtils.firstNonNull(ENTITIES_BY_KEYNAME.get("CVE_CNA_GITHUB_M"), ENTITIES_BY_NAME.get("GitHub, Inc."));
Why is OSV equivalent to GHSA?

2024-12-09 07:54 UTC, karsten-klein reviewed
Needs two fixes; there are dedicated comments

2024-12-15 15:25 UTC, karsten-klein approved these changes

2025-01-05 16:29 UTC, karsten-klein approved these changes

2025-01-05 16:34 UTC, karsten-klein requested changes

2025-01-05 16:34 UTC, karsten-klein commented on libraries/ae-inventory-processor/src/main/java/org/metaeffekt/core/inventory/processor/report/configuration/CentralSecurityPolicyConfiguration.java
> +
Is this a duplication; why twice?

2025-01-05 16:34 UTC, karsten-klein commented on libraries/ae-inventory-processor/src/main/java/org/metaeffekt/core/inventory/processor/report/model/aeaa/AeaaDataSourceIndicator.java
> +    @Getter
Why @Getter here?

2025-01-09 13:00 UTC, juliankomarek commented on libraries/ae-inventory-processor/src/main/java/org/metaeffekt/core/inventory/processor/report/model/aeaa/AeaaDataSourceIndicator.java
> +    @Getter
was by accident, fixed it

2025-01-09 13:53 UTC, karsten-klein approved these changes

2025-01-09 13:53 UTC, karsten-klein commented on libraries/ae-inventory-processor/src/main/java/org/metaeffekt/core/inventory/processor/report/configuration/CentralSecurityPolicyConfiguration.java
> +
My fault

2025-01-09 13:53 UTC, merged